### ISSUE TITLE
readiab subsection 404 file not found

### ISSUE THREAD

**Issue by reputri** [applied-bioinformatics/iab2#3]
Hi, 

I found https://readiab.org/book/latest/3/1#4 a while ago for my learning. But apparently the website is no longer working. Could you please fix the issue ?

**Comment by gregcaporaso** [comment]
I realize this is a very old comment that I never responded to - sorry about that! 

The version of the book that you were referred has been succeeded by [IAB 2nd Edition](http://readIAB.org). I believe you were looking for the _Studying Microbial Diversity_ chapter, which I decided to migrate from IAB to my [q2book project](https://gregcaporaso.github.io/q2book/front-matter/preface.html). If you're still interested in this content, you can find in there. Hope this helps!
