### ISSUE TITLE
http://readIAB.org site shows 404 error

### ISSUE THREAD

**Issue by colinbrislawn** [applied-bioinformatics/iab2#5]
![image](https://user-images.githubusercontent.com/10355152/221656251-80746e82-9ea1-47f0-a689-2219ce3af640.png)

**Comment by Sohambiswas8** [comment]
Yes, I am having the same issue in opening the site. When I first started IAB back in December last year, the webpage was opening. I think it is not responding for almost last two months

**Comment by gregcaporaso** [comment]
I missed this issue till now, sorry! 

I'm working on fixing this, but in the meantime the book can be found [here](https://applied-bioinformatics.github.io/iab2/introduction.html).

**Comment by Sohambiswas8** [comment]
Thank you so much. The book is really well-written and designed and much appreciated. Definitely recommendable to anyone who is a beginner in bioinformatics. Also helpful for someone who would like to brush up on concepts again.

**Comment by gregcaporaso** [comment]
This is fixed now. Thanks again for bringing it to my attention!
